/**
 * 
 */
package adn.controller;

import static adn.application.context.ContextProvider.getPrincipalCredential;
import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.http.ResponseEntity.ok;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.annotation.Secured;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import adn.application.Common;
import adn.controller.query.impl.ProductQuery;
import adn.dao.generic.ResultBatch;
import adn.helpers.StringHelper;
import adn.model.entities.Category;
import adn.model.entities.Product;
import adn.model.entities.StockDetail;
import adn.model.factory.authentication.dynamicmap.UnauthorizedCredential;
import adn.model.models.StockDetailBatch;
import adn.service.internal.ResourceService;
import adn.service.internal.Service.Status;
import adn.service.services.AuthenticationService;
import adn.service.services.CategoryService;
import adn.service.services.GenericFactorService;
import adn.service.services.ProductService;

/**
 * @author Ngoc Huy
 *
 */
@RestController
@RequestMapping("/rest/product")
public class RestProductController extends ProductController {

	private final CategoryService categoryService;

	@Autowired
	public RestProductController(AuthenticationService authService, ProductService productService,
			ResourceService resourceService, CategoryService categoryService,
			GenericFactorService genericFactorService) {
		super(authService, productService, resourceService, genericFactorService);
		this.categoryService = categoryService;
	}

	@GetMapping(path = "/count")
	@Transactional(readOnly = true)
	public ResponseEntity<?> getProductCount() {
		return makeStaleWhileRevalidate(ResponseEntity.ok(genericFactorService.count(Product.class)), 2,
				TimeUnit.DAYS, 7, TimeUnit.DAYS);
	}

	@GetMapping(path = "/{productId}")
	@Transactional(readOnly = true)
	public ResponseEntity<?> obtainProduct(@PathVariable(name = "productId", required = true) String productId,
			@RequestParam(name = "columns", required = false, defaultValue = "") List<String> columns)
			throws NoSuchFieldException, UnauthorizedCredential {
		return send(genericFactorService.readById(Product.class, productId, columns, getPrincipalCredential()),
				String.format("Product %s not found", productId));
	}

	@GetMapping
	@Transactional(readOnly = true)
	public ResponseEntity<?> getProducts(
			@RequestParam(name = "category", required = false, defaultValue = "") String categoryId,
			@RequestParam(name = "by", required = false, defaultValue = "") String identifierName,
			@RequestParam(name = "columns", required = false, defaultValue = "") List<String> columns,
			@PageableDefault(size = 10) Pageable paging) throws NoSuchFieldException, UnauthorizedCredential {
		if (StringHelper.hasLength(categoryId)) {
			return ok(productService.getProductsByCategory(categoryId, identifierName, columns, paging,
					getPrincipalCredential()));
		}

		return ok(genericFactorService.readAll(Product.class, columns, paging, getPrincipalCredential()));
	}

	@GetMapping(path = "/search")
	@Transactional(readOnly = true)
	public ResponseEntity<?> searchForProducts(ProductQuery query,
			@RequestParam(name = "columns", required = false, defaultValue = "") List<String> columns,
			@PageableDefault(size = 10) Pageable paging) throws NoSuchFieldException, UnauthorizedCredential {
		if (!query.hasCriteria()) {
			return sendBad(Common.INVALID_SEARCH_CRITERIA);
		}

		return ResponseEntity.ok(productService.searchProduct(columns, paging, query, getPrincipalCredential()));
	}

	@PostMapping(path = "/category", consumes = APPLICATION_JSON_VALUE, produces = APPLICATION_JSON_VALUE)
	@Secured({ HEAD, PERSONNEL })
	@Transactional
	public ResponseEntity<?> createCategory(@RequestBody Category category) throws UnauthorizedCredential {
		authService.assertSaleDepartment();
		// we dont't have to check for id here since it will be generated by
		// IdentifierGenerator and service layer
		return send(categoryService.createCategory(category, true));
	}

	@PutMapping(path = "/category", consumes = APPLICATION_JSON_VALUE, produces = APPLICATION_JSON_VALUE)
	@Secured({ HEAD, PERSONNEL })
	@Transactional
	public ResponseEntity<?> updateCategory(@RequestBody Category model) throws UnauthorizedCredential {
		authService.assertSaleDepartment();

		Optional<Category> optional = baseRepository.findById(Category.class, model.getId());

		if (optional.isEmpty()) {
			return sendNotFound(String.format("Category %s not found", model.getId()));
		}

		return send(crudService.update(optional.get().getId(), model, Category.class, true));
	}

	@GetMapping("/category/list")
	@Transactional(readOnly = true)
	@Secured({ HEAD, PERSONNEL })
	public ResponseEntity<?> getCategoryList(@PageableDefault(size = 5) Pageable pageable,
			@RequestParam(name = "columns", defaultValue = "") List<String> columns)
			throws NoSuchFieldException, UnauthorizedCredential {
		return send(crudService.readAll(Category.class, columns, pageable, getPrincipalCredential()), null);
	}

	@GetMapping("/category/all")
	@Transactional(readOnly = true)
	public ResponseEntity<?> getAllCategories() throws NoSuchFieldException, UnauthorizedCredential {
		return makeStaleWhileRevalidate(genericFactorService.readAll(Category.class, Arrays.asList("id", "name"),
				PageRequest.of(0, 1000), getPrincipalCredential()), 1, TimeUnit.DAYS, 2, TimeUnit.DAYS);
	}

	@GetMapping("/category/count")
	@Transactional(readOnly = true)
	public ResponseEntity<?> getCategoryCount() {
		return makeStaleWhileRevalidate(genericFactorService.count(Category.class), 1, TimeUnit.DAYS, 3,
				TimeUnit.DAYS);
	}

	@PatchMapping("/category/activation")
	@Transactional
	public ResponseEntity<?> deactivateCategory(@RequestParam(name = "id", required = true) String categoryId,
			@RequestParam(name = "active", required = true) Boolean requestedActiveState) {
		authService.assertSaleDepartment();

		Optional<Category> optional = baseRepository.findById(Category.class, categoryId);

		if (optional.isEmpty()) {
			return sendNotFound(Common.NOT_FOUND);
		}

		Category category = optional.get();
		// we use AUTO-FLUSH here
		category.setActive(requestedActiveState);

		if (requestedActiveState == false) {
			category.setDeactivatedTimestamp(LocalDateTime.now());
			category.setUpdatedBy(authService.getOperator());
		}

		return send(String.format("Modified activation state of category %s", categoryId), null);
	}

	@PostMapping("/stockdetail")
	@Secured({ HEAD, PERSONNEL })
	@Transactional
	public ResponseEntity<?> createStockDetails(@RequestBody(required = true) StockDetailBatch batch) {
		authService.assertStockDepartment();

		ResultBatch<StockDetail> results = crudService.createBatch(batch.getDetails(), StockDetail.class, true);

		if (results.isOk()) {
			return ResponseEntity.ok(results.getResults().stream().map(result -> {
				try {
					return dynamicMapModelFactory.producePojo(result.getInstance(), null, getPrincipalCredential());
				} catch (UnauthorizedCredential e) {
					return e.getMessage();
				}
			}).collect(Collectors.toList()));
		}

		if (results.getStatus() == Status.BAD) {
			return sendBad(
					results.getResults().stream().map(result -> result.getMessages()).collect(Collectors.toList()));
		}

		return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(Common.FAILED);
	}

}
