/**
 * 
 */
package adn.model.specification.generic;

import java.io.Serializable;

import adn.dao.DatabaseInteractionResult;
import adn.helpers.EntityUtils;
import adn.model.entities.Entity;
import adn.model.specification.Specification;
import adn.model.specification.TransactionalSpecification;

/**
 * @author Ngoc Huy
 *
 */
public abstract class EntitySpecification<T extends Entity> extends TransactionalSpecification<T>
		implements Specification<T> {

	@Override
	public DatabaseInteractionResult<T> isSatisfiedBy(Serializable id, T instance) {
		DatabaseInteractionResult<T> result = new DatabaseInteractionResult<>(instance);

		if (id == null && !EntityUtils.isIdentifierAutoGenerated(instance.getClass())) {
			result.bad().getMessages().put("id", "Id can not be empty");
		}

		return result;
	}

	@Override
	public DatabaseInteractionResult<T> isSatisfiedBy(T instance) {
		return isSatisfiedBy(EntityUtils.getIdentifier(instance), instance);
	}

}
