/**
 * 
 */
package adn.helpers;

import java.io.Serializable;

import org.hibernate.engine.spi.SessionFactoryImplementor;

import adn.application.context.ContextProvider;
import adn.model.entities.Entity;

/**
 * @author Ngoc Huy
 *
 */
public class EntityUtils {

	private EntityUtils() {}

	public static <T extends Entity> Serializable getIdentifier(T entity) {
		// @formatter:off
		return ContextProvider.getApplicationContext()
				.getBean(SessionFactoryImplementor.class).getMetamodel()
				.entityPersister(entity.getClass())
				.getIdentifier(entity, null);
		// @formatter:on
		// session arg is not required, at least if the Session is instance of
		// org.hibernate.internal.SessionImpl
	}

	public static <T extends Entity> boolean isIdentifierAutoGenerated(Class<T> type) {
		// @formatter:off
		return ContextProvider.getApplicationContext()
				.getBean(SessionFactoryImplementor.class).getMetamodel()
				.entityPersister(type).getEntityMetamodel()
				.getIdentifierProperty().getIdentifierGenerator() != null;
		// @formatter:on
	}

}
