/**
 * 
 */
package adn.service.resource.local;

import java.io.Serializable;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.Stream;

import javax.persistence.metamodel.Attribute;
import javax.persistence.metamodel.SingularAttribute;

import org.hibernate.HibernateException;
import org.hibernate.LockMode;
import org.hibernate.LockOptions;
import org.hibernate.MappingException;
import org.hibernate.bytecode.spi.BytecodeEnhancementMetadata;
import org.hibernate.engine.internal.MutableEntityEntryFactory;
import org.hibernate.engine.spi.CascadeStyle;
import org.hibernate.engine.spi.EntityEntryFactory;
import org.hibernate.engine.spi.SessionFactoryImplementor;
import org.hibernate.engine.spi.SharedSessionContractImplementor;
import org.hibernate.engine.spi.ValueInclusion;
import org.hibernate.id.IdentifierGenerator;
import org.hibernate.internal.FilterAliasGenerator;
import org.hibernate.metadata.ClassMetadata;
import org.hibernate.persister.entity.MultiLoadOptions;
import org.hibernate.persister.walking.spi.AttributeDefinition;
import org.hibernate.persister.walking.spi.EntityIdentifierDefinition;
import org.hibernate.property.access.spi.PropertyAccess;
import org.hibernate.tuple.ValueGeneration;
import org.hibernate.type.Type;
import org.hibernate.type.VersionType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.util.Assert;

import adn.application.context.ContextProvider;
import adn.service.resource.metamodel.EntityBinder;
import adn.service.resource.metamodel.EntityPersisterImplementor;
import adn.service.resource.metamodel.EntityTuplizerImplementor;
import adn.service.resource.metamodel.MetamodelImpl;
import adn.service.resource.metamodel.MetamodelImpl.IdentifierGenerationHolder;
import adn.service.resource.metamodel.MetamodelImpl.NoValueGeneration;
import adn.service.resource.metamodel.PropertyBinder;
import adn.service.resource.metamodel.ResourceType;

/**
 * @author Ngoc Huy
 *
 */
public class ResourcePersisterImpl<D> implements ResourcePersister<D>, EntityPersisterImplementor<D>, ClassMetadata {

	private final Logger logger = LoggerFactory.getLogger(MetamodelImpl.class);

	private final ResourceManagerFactory managerFactory;
	private final ResourceType<D> metamodel;

	private String entityName;
	private Class<D> mappedClass;

	private PropertyAccess identifierAccess;
	private IdentifierGenerator identifierGenerator;

	private int propertySpan;
	private final Map<String, Integer> indexMap = new HashMap<>();
	private PropertyAccess[] propertyAccesses;
	private ValueGeneration[] valueGenerations;
	private Class<?>[] propertyTypes;
	private boolean[] autoGeneratedMarkers;
	private boolean[] propertyNullabilities;
	private boolean[] propertyUpdatabilities;
	// Every resource instances is mutable
	private final EntityEntryFactory entryFactory = MutableEntityEntryFactory.INSTANCE;

	public ResourcePersisterImpl(ResourceManagerFactory managerFactory, ResourceType<D> metamodel) {
		// TODO Auto-generated constructor stub
		Assert.notNull(managerFactory, "ResourceManagerFactory must not be null");
		Assert.notNull(metamodel, "EntityTypeImpl must not be null");
		this.managerFactory = managerFactory;
		this.metamodel = metamodel;
	}

	@Override
	public void generateEntityDefinition() {
		// TODO Auto-generated method stub
		mappedClass = metamodel.getJavaType();
		logger.trace("Generating entity definition of type " + mappedClass.getName());
		entityName = metamodel.getName();
		propertySpan = determinePropertySpan(metamodel);
		propertyAccesses = new PropertyAccess[propertySpan];
		valueGenerations = new ValueGeneration[propertySpan];
		propertyTypes = new Class<?>[propertySpan];
		autoGeneratedMarkers = new boolean[propertySpan];
		propertyNullabilities = new boolean[propertySpan];
		propertyUpdatabilities = new boolean[propertySpan];

		@SuppressWarnings("unchecked")
		Attribute<D, ?>[] attributes = metamodel.getAttributes().toArray(Attribute[]::new);

		for (int i = 0; i < propertySpan; i++) {
			Attribute<D, ?> attr = attributes[i];

			indexMap.put(attr.getName(), i);

			ValueGeneration delegateGeneration;

			if (!attr.getDeclaringType().equals(metamodel)) {
				logger.trace("Locating metadata from super type");
				propertyAccesses[i] = locatePropertyAccess(attr.getName());
				valueGenerations[i] = (delegateGeneration = locateValueGeneration(attr.getName()));
			} else {
				propertyAccesses[i] = PropertyBinder.INSTANCE.createPropertyAccess(mappedClass, attr.getName());
				valueGenerations[i] = (delegateGeneration = PropertyBinder.INSTANCE.resolveValueGeneration(metamodel,
						attr));
			}

			propertyNullabilities[i] = attr instanceof SingularAttribute
					? ((SingularAttribute<? super D, ?>) attr).isOptional()
					: Optional
							.ofNullable(attr.getJavaMember() instanceof Field
									? PropertyBinder.INSTANCE.isOptional((Field) attr.getJavaMember())
									: null)
							.orElseThrow(() -> new IllegalArgumentException(
									"Unable to determine nullability of attribute " + attr.getName()));
			propertyUpdatabilities[i] = attr.getJavaMember() instanceof Field
					? PropertyBinder.INSTANCE.isUpdatable((Field) attr.getJavaMember())
					: true;
			propertyTypes[i] = attr.getJavaType();
			logger.trace(String.format(
					"Located valuegeneration of attribute %s. GenerationTiming %s. ValueGenerator %s", attr.getName(),
					delegateGeneration == IdentifierGenerationHolder.INSTANCE ? "determined by IdentifierGenerator"
							: delegateGeneration.getGenerationTiming(),
					delegateGeneration.getValueGenerator() != null
							? delegateGeneration.getValueGenerator().getClass().getName()
							: delegateGeneration == IdentifierGenerationHolder.INSTANCE
									? "determined by IdentifierGenerator"
									: "NULL"));
			autoGeneratedMarkers[i] = (delegateGeneration != NoValueGeneration.INSTANCE);
		}

		if (metamodel.hasSingleIdAttribute()) {
			identifierAccess = propertyAccesses[indexMap
					.get(metamodel.getId(metamodel.getIdType().getJavaType()).getName())];
			try {
				identifierGenerator = EntityBinder.INSTANCE.locateIdentifierGenerator(metamodel, managerFactory);
			} catch (IllegalAccessException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				SpringApplication.exit(ContextProvider.getApplicationContext());
			}
		}
	}

	private int determinePropertySpan(ResourceType<? super D> metamodel) {
		if (metamodel.getSupertype() == null) {
			return metamodel.getDeclaredAttributes().size();
		}

		return metamodel.getDeclaredAttributes().size() + determinePropertySpan(metamodel.locateSuperType());
	}

	@Override
	public void postInstantiate() throws MappingException {
		// TODO Auto-generated method stub
		logger.trace("Finished instantiating ResourcePersister for resource named " + getEntityName());
	}

	@Override
	public EntityEntryFactory getEntityEntryFactory() {
		// TODO Auto-generated method stub
		return entryFactory;
	}

	@Override
	public String getRootEntityName() {
		// TODO Auto-generated method stub
		return metamodel.locateRootType().getName();
	}

	@Override
	public String getEntityName() {
		// TODO Auto-generated method stub
		return entityName;
	}

	@Override
	public boolean isSubclassEntityName(String entityName) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public Serializable[] getPropertySpaces() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Serializable[] getQuerySpaces() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean hasProxy() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean hasCollections() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean hasMutableProperties() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean hasSubselectLoadableCollections() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean hasCascades() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean isMutable() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean isInherited() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean isIdentifierAssignedByInsert() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public Type getPropertyType(String propertyName) throws MappingException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public int[] findDirty(Object[] currentState, Object[] previousState, Object owner,
			SharedSessionContractImplementor session) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public int[] findModified(Object[] old, Object[] current, Object object, SharedSessionContractImplementor session) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean hasIdentifierProperty() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean canExtractIdOutOfEntity() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean isVersioned() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public VersionType getVersionType() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public int getVersionProperty() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public boolean hasNaturalIdentifier() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public int[] getNaturalIdentifierProperties() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Object[] getNaturalIdentifierSnapshot(Serializable id, SharedSessionContractImplementor session) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public IdentifierGenerator getIdentifierGenerator() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean hasLazyProperties() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public Serializable loadEntityIdByNaturalId(Object[] naturalIdValues, LockOptions lockOptions,
			SharedSessionContractImplementor session) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Object load(Serializable id, Object optionalObject, LockMode lockMode,
			SharedSessionContractImplementor session) throws HibernateException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Object load(Serializable id, Object optionalObject, LockOptions lockOptions,
			SharedSessionContractImplementor session) throws HibernateException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List multiLoad(Serializable[] ids, SharedSessionContractImplementor session, MultiLoadOptions loadOptions) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void lock(Serializable id, Object version, Object object, LockMode lockMode,
			SharedSessionContractImplementor session) throws HibernateException {
		// TODO Auto-generated method stub

	}

	@Override
	public void lock(Serializable id, Object version, Object object, LockOptions lockOptions,
			SharedSessionContractImplementor session) throws HibernateException {
		// TODO Auto-generated method stub

	}

	@Override
	public void insert(Serializable id, Object[] fields, Object object, SharedSessionContractImplementor session)
			throws HibernateException {
		// TODO Auto-generated method stub

	}

	@Override
	public Serializable insert(Object[] fields, Object object, SharedSessionContractImplementor session)
			throws HibernateException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void delete(Serializable id, Object version, Object object, SharedSessionContractImplementor session)
			throws HibernateException {
		// TODO Auto-generated method stub

	}

	@Override
	public void update(Serializable id, Object[] fields, int[] dirtyFields, boolean hasDirtyCollection,
			Object[] oldFields, Object oldVersion, Object object, Object rowId,
			SharedSessionContractImplementor session) throws HibernateException {
		// TODO Auto-generated method stub

	}

	@Override
	public Type[] getPropertyTypes() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String[] getPropertyNames() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean[] getPropertyInsertability() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ValueInclusion[] getPropertyInsertGenerationInclusions() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ValueInclusion[] getPropertyUpdateGenerationInclusions() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean[] getPropertyUpdateability() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean[] getPropertyCheckability() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean[] getPropertyNullability() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean[] getPropertyVersionability() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean[] getPropertyLaziness() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public CascadeStyle[] getPropertyCascadeStyles() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Type getIdentifierType() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getIdentifierPropertyName() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ClassMetadata getClassMetadata() {
		// TODO Auto-generated method stub
		return this;
	}

	@Override
	public boolean isBatchLoadable() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean isSelectBeforeUpdateRequired() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public Object[] getDatabaseSnapshot(Serializable id, SharedSessionContractImplementor session)
			throws HibernateException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Serializable getIdByUniqueKey(Serializable key, String uniquePropertyName,
			SharedSessionContractImplementor session) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Object getCurrentVersion(Serializable id, SharedSessionContractImplementor session)
			throws HibernateException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Object forceVersionIncrement(Serializable id, Object currentVersion,
			SharedSessionContractImplementor session) throws HibernateException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean isInstrumented() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean hasInsertGeneratedProperties() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean hasUpdateGeneratedProperties() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean isVersionPropertyGenerated() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void afterInitialize(Object entity, SharedSessionContractImplementor session) {
		// TODO Auto-generated method stub

	}

	@Override
	public void afterReassociate(Object entity, SharedSessionContractImplementor session) {
		// TODO Auto-generated method stub

	}

	@Override
	public Object createProxy(Serializable id, SharedSessionContractImplementor session) throws HibernateException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Boolean isTransient(Object object, SharedSessionContractImplementor session) throws HibernateException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Object[] getPropertyValuesToInsert(Object object, Map mergeMap, SharedSessionContractImplementor session)
			throws HibernateException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void processInsertGeneratedProperties(Serializable id, Object entity, Object[] state,
			SharedSessionContractImplementor session) {
		// TODO Auto-generated method stub

	}

	@Override
	public void processUpdateGeneratedProperties(Serializable id, Object entity, Object[] state,
			SharedSessionContractImplementor session) {
		// TODO Auto-generated method stub

	}

	@Override
	public Class<D> getMappedClass() {
		// TODO Auto-generated method stub
		return mappedClass;
	}

	@Override
	public boolean implementsLifecycle() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public Class getConcreteProxyClass() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setPropertyValues(Object object, Object[] values) {
		// TODO Auto-generated method stub

	}

	@Override
	public void setPropertyValue(Object object, int i, Object value) {
		// TODO Auto-generated method stub

	}

	@Override
	public Object[] getPropertyValues(Object object) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Object getPropertyValue(Object object, int i) throws HibernateException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Object getPropertyValue(Object object, String propertyName) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Serializable getIdentifier(Object object) throws HibernateException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Serializable getIdentifier(Object entity, SharedSessionContractImplementor session) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setIdentifier(Object entity, Serializable id, SharedSessionContractImplementor session) {
		// TODO Auto-generated method stub

	}

	@Override
	public Object getVersion(Object object) throws HibernateException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Object instantiate(Serializable id, SharedSessionContractImplementor session) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean isInstance(Object object) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean hasUninitializedLazyProperties(Object object) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void resetIdentifier(Object entity, Serializable currentId, Object currentVersion,
			SharedSessionContractImplementor session) {
		// TODO Auto-generated method stub

	}

	@Override
	public EntityTuplizerImplementor<D> getEntityTuplizer() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public BytecodeEnhancementMetadata getInstrumentationMetadata() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public FilterAliasGenerator getFilterAliasGenerator(String rootAlias) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public int[] resolveAttributeIndexes(String[] attributeNames) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public EntityIdentifierDefinition getEntityKeyDefinition() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Iterable<AttributeDefinition> getAttributes() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ResourcePersister<D> getSubclassEntityPersister(Object instance, SessionFactoryImplementor factory) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ResourcePersister<D> getEntityPersister() {
		// TODO Auto-generated method stub
		return this;
	}

	@Override
	public ResourceManagerFactory getManagerFactory() {
		// TODO Auto-generated method stub
		return managerFactory;
	}

	@Override
	public boolean hasSubclasses() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void setPropertyValue(Object object, String propertyName, Object value) throws HibernateException {
		// TODO Auto-generated method stub
	}

	@SuppressWarnings("unchecked")
	@Override
	public <E extends ResourcePersister<D>> E unwrap(Class<? super E> type) {
		// TODO Auto-generated method stub
		return (E) this;
	}

	@Override
	public String toString() {
		// @formatter:off
		return String.format("Metamodel: %s\n"
				+ "\t-propertySpan: %d\n"
				+ "\t-indexMap: [%s]\n"
				+ "\t-valueGenerations: [%s]\n"
				+ "\t-propertyNullabilities: [%s]\n"
				+ "\t-propertyUpdatabilities: [%s]\n"
				+ "\t-propertyTypes: [%s]\n"
				+ "\t-getters: [%s]\n"
				+ "\t-setters: [%s]\n"
				+ "\t-autoGeneratedMarkers: [%s]\n"
				+ "\t-identifierGenerator: %s\n"
				+ "\t-superType: %s\n"
				+ "\t-declaredAttributes: \n%s\n"
				+ "\t-declaredSingularAttributes: \n%s\n"
				+ "\t-declaredPluralAttributes: \n%s\n"
				+ "\t-hasIdentifierProperty: %b\n"
				+ "\t-hasIdClass: %b\n"
				+ "\t-id: %s\n"
				+ "\t-idClassAttributes(in size): %d\n"
				+ "\t-isVersioned: %b\n"
				+ "\t-versionAttribute: %s\n"
				+ "\t-subclassNames: %s",
				getEntityName(),
				propertySpan,
				indexMap.entrySet().stream().sorted((l, r) -> Integer.compare(l.getValue(), r.getValue())).map(ele -> ele.getValue() + "|" + ele.getKey()).collect(Collectors.joining(", ")),
				Stream.of(valueGenerations)
					.map(ele -> {
						if (ele instanceof IdentifierGenerationHolder) {
							return "Determined by IdentifierGenerator|Generated by IdentifierGenerator";
						}
						
						return ele.getGenerationTiming() + "|" + (ele.getValueGenerator() != null ? ele.getValueGenerator().getClass().getName() : "NULL");
					})
					.collect(Collectors.joining(", ")),
				IntStream.range(0, propertySpan)
					.mapToObj(index -> String.valueOf(propertyNullabilities[index]))
					.collect(Collectors.joining(", ")),
				IntStream.range(0, propertySpan)
					.mapToObj(index -> String.valueOf(propertyUpdatabilities[index]))
					.collect(Collectors.joining(", ")),
				Stream.of(propertyTypes)
					.map(ele -> ele.getName())
					.collect(Collectors.joining(", ")),
				Stream.of(propertyAccesses)
					.map(pa -> pa.getGetter().getMethod().getName())
					.collect(Collectors.joining(", ")),
				Stream.of(propertyAccesses)
					.map(pa -> pa.getSetter().getMethod().getName())
					.collect(Collectors.joining(", ")),	
				IntStream.range(0, propertySpan)
					.mapToObj(index -> String.valueOf(autoGeneratedMarkers[index]))
					.collect(Collectors.joining(", ")),
				identifierGenerator != null ? identifierGenerator.getClass().getName() : "NULL",
				metamodel.getSupertype() != null ? metamodel.getSupertype().getName() : "NULL",
				metamodel.getDeclaredAttributes().stream().map(ele -> String.format("\t\t-name: %s\n"
						+ "\t\t-persistentAttributeType: %s\n"
						+ "\t\t-declaringType: %s\n"
						+ "\t\t-javaMember: %s\n"
						+ "\t\t-isAssociation: %b\n"
						+ "\t\t-isCollection: %b",
						ele.getName(),
						ele.getPersistentAttributeType(),
						ele.getDeclaringType().getJavaType(),
						ele.getJavaMember().getName(),
						ele.isAssociation(),
						ele.isCollection())).collect(Collectors.joining("\n\t\t--------------------\n")),
				metamodel.getDeclaredSingularAttributes().stream().map(ele -> String.format("\t\t-name: %s\n"
						+ "\t\t-isId: %b\n"
						+ "\t\t-isVersion: %b\n"
						+ "\t\t-isOptional: %b", 
						ele.getName(),
						ele.isId(),
						ele.isVersion(),
						ele.isOptional())).collect(Collectors.joining("\n\t\t--------------------\n")),
				metamodel.getDeclaredPluralAttributes().stream().map(ele -> String.format("\t\t-name: %s\n"
						+ "\t\t-collectionType: %s\n"
						+ "\t\t-elementType: %s\n",
						ele.getName(),
						ele.getCollectionType(),
						ele.getElementType().getJavaType().getName())).collect(Collectors.joining("\n\t\t--------------------\n")),
				metamodel.hasSingleIdAttribute(),
				metamodel.hasIdClass(),
				metamodel.hasSingleIdAttribute() ? metamodel.getId(metamodel.getIdType().getJavaType()).getName() + ": " + metamodel.getId(metamodel.getIdType().getJavaType()).getJavaType().getName() : "NULL",
				metamodel.hasIdClass() ? metamodel.getIdClassAttributes().size() : 0,
				metamodel.hasVersionAttribute(),
				metamodel.hasVersionAttribute() ? metamodel.getDeclaredVersion().getName() + ": " + metamodel.getDeclaredVersion().getJavaType().getName() : "NULL",
				metamodel.getSubclassNames().stream().collect(Collectors.joining(", ")));
		// @formatter:on
	}

	@Override
	public PropertyAccess getPropertyAccess(String propertyName) {
		// TODO Auto-generated method stub
		return propertyAccesses[indexMap.get(propertyName)];
	}

	@Override
	public PropertyAccess getPropertyAccess(int propertyIndex) {
		// TODO Auto-generated method stub
		return propertyAccesses[propertyIndex];
	}

	@Override
	public PropertyAccess locatePropertyAccess(String propertyName) {
		PropertyAccess candidate = getPropertyAccess(propertyName);

		if (candidate != null) {
			return candidate;
		}

		return managerFactory.getMetamodel().entityPersister(metamodel.locateSuperType().getName())
				.locatePropertyAccess(propertyName);
	}

	@Override
	public ValueGeneration getValueGeneration(int propertyIndex) {
		// TODO Auto-generated method stub
		return valueGenerations[propertyIndex];
	}

	@Override
	public ValueGeneration getValueGeneration(String propertyName) {
		// TODO Auto-generated method stub
		return valueGenerations[indexMap.get(propertyName)];
	}

	@Override
	public ValueGeneration locateValueGeneration(String propertyName) {
		// TODO Auto-generated method stub
		ValueGeneration candidate = getValueGeneration(propertyName);

		if (candidate != null) {
			return candidate;
		}

		return managerFactory.getMetamodel().entityPersister(metamodel.locateSuperType().getName())
				.locateValueGeneration(propertyName);
	}

}
