/**
 * 
 */
package adn.model.entities.validator;

import java.io.Serializable;

import org.hibernate.Session;

import adn.dao.generic.Result;
import adn.helpers.HibernateHelper;
import adn.model.entities.Entity;

/**
 * @author Ngoc Huy
 *
 */
public abstract class AbstractEntityValidator<T extends Entity> implements Validator<T> {

	@Override
	public Result<T> isSatisfiedBy(Session session, T instance) {
		return isSatisfiedBy(session, HibernateHelper.getIdentifier(instance), instance);
	}

	@Override
	public Result<T> isSatisfiedBy(Session session, Serializable id, T instance) {
		Result<T> result = new Result<>(instance);

		if (id == null && !HibernateHelper.isIdentifierAutoGenerated(instance.getClass())) {
			result.bad().getMessages().put("id", "Id can not be empty");
		}

		return result;
	}

}
