/**
 * 
 */
package adn.service.entity.builder;

import java.io.Serializable;

import org.hibernate.Session;
import org.hibernate.persister.entity.EntityPersister;

import adn.helpers.HibernateHelper;
import adn.model.entities.Entity;

/**
 * @author Ngoc Huy
 *
 */
public abstract class AbstractEntityBuilder<T extends Entity> extends EntityBuilderContract<T> {

	public static final String CODE_GENERATION_MESSAGE = "Generating encrypted code for an entity with id: [%s]";

	protected <E extends T> E mandatoryBuild(E target, E model) {
		return target;
	}

	@Override
	public <E extends T> E buildInsertion(Serializable id, E model, Session session) {
		Class<? extends Entity> type = model.getClass();
		// to avoid unique column constraint violation when callers
		// explicitly set an existing id into the model.
		// This will cause the Specification check on name uniqueness to pass
		// while it shouldn't have
		if (HibernateHelper.isIdentifierAutoGenerated(type)) {
			id = null;

			EntityPersister persister = HibernateHelper.getEntityPersister(type);
			// there is a tiny chance that we need the Session here,
			// according to Hibernate documents. Thus null
			persister.setIdentifier(model, null, null);
		}

		return mandatoryBuild(model, model);
	}

	@Override
	public <E extends T> E buildUpdate(Serializable id, E model, E persistence, Session session) {
		return mandatoryBuild(persistence, model);
	}

	@Override
	public <E extends T> E buildPostValidationOnInsert(Serializable id, E model, Session session) {
		return model;
	}

}
