export const SET_VIEW = "SET_VIEW";
export const SET_LIST = "SET_LIST";
export const SET_AMOUNT = "SET_AMOUNT";
export const SET_PAGE = "SET_PAGE";
export const SET_ERROR = "SET_ERROR";
export const SET_MODEL = "SET_MODEL";
export const SET_ACTION = "SET_ACTION";
export const SET_INDIVIDUAL_VIEW_TARGET = "SET_INDIVIDUAL_VIEW_TARGET";
export const SET_LIST_ELEMENT = "SET_LIST_ELEMENT";

export const FULFILL_PAGE = "FULFILL_PAGE";

export const MODIFY_MODEL = "MODIFY_MODEL";
export const MODIFY_PAGINATION_STATE = "MODIFY_PAGINATION_STATE";

export const PUSH_LIST = "PUSH_LIST";

export const CREATE = "CREATE";
export const EDIT = "EDIT";

export const TOGGLE_INDIVIDUAL_VIEW_VISION = "TOGGLE_INDIVIDUAL_VIEW_VISION";
export const TOGGLE_FORM_VISION = "TOGGLE_FORM_VISION";
export const TOGGLE_LIST_VISION = "TOGGLE_LIST_VISION";